// ============================================================
// Real F1 Track Data — 2024 season calendar inspired
// ============================================================

import type { TrackConfig } from '@/types/engine';

export const TRACKS: TrackConfig[] = [
  {
    name: 'Bahrain International Circuit',
    country: 'Bahrain',
    lengthKm: 5.412,
    totalLaps: 57,
    baseLapTime: 92.0,
    pitLaneTime: 23.5,
    tireWearMultiplier: 1.15,
    overtakeDifficulty: 0.35,
    drsZones: 3,
    sectors: 3,
  },
  {
    name: 'Jeddah Corniche Circuit',
    country: 'Saudi Arabia',
    lengthKm: 6.174,
    totalLaps: 50,
    baseLapTime: 89.5,
    pitLaneTime: 25.0,
    tireWearMultiplier: 1.0,
    overtakeDifficulty: 0.4,
    drsZones: 3,
    sectors: 3,
  },
  {
    name: 'Albert Park Circuit',
    country: 'Australia',
    lengthKm: 5.278,
    totalLaps: 58,
    baseLapTime: 79.5,
    pitLaneTime: 22.0,
    tireWearMultiplier: 1.05,
    overtakeDifficulty: 0.5,
    drsZones: 4,
    sectors: 3,
  },
  {
    name: 'Suzuka International Racing Course',
    country: 'Japan',
    lengthKm: 5.807,
    totalLaps: 53,
    baseLapTime: 91.0,
    pitLaneTime: 24.0,
    tireWearMultiplier: 1.1,
    overtakeDifficulty: 0.65,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Shanghai International Circuit',
    country: 'China',
    lengthKm: 5.451,
    totalLaps: 56,
    baseLapTime: 95.0,
    pitLaneTime: 24.5,
    tireWearMultiplier: 1.0,
    overtakeDifficulty: 0.4,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Miami International Autodrome',
    country: 'USA',
    lengthKm: 5.412,
    totalLaps: 57,
    baseLapTime: 89.0,
    pitLaneTime: 23.0,
    tireWearMultiplier: 1.1,
    overtakeDifficulty: 0.4,
    drsZones: 3,
    sectors: 3,
  },
  {
    name: 'Autodromo Enzo e Dino Ferrari',
    country: 'Italy',
    lengthKm: 4.909,
    totalLaps: 63,
    baseLapTime: 76.5,
    pitLaneTime: 22.5,
    tireWearMultiplier: 0.95,
    overtakeDifficulty: 0.55,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Circuit de Monaco',
    country: 'Monaco',
    lengthKm: 3.337,
    totalLaps: 78,
    baseLapTime: 73.0,
    pitLaneTime: 21.0,
    tireWearMultiplier: 0.8,
    overtakeDifficulty: 0.9,
    drsZones: 1,
    sectors: 3,
  },
  {
    name: 'Circuit Gilles Villeneuve',
    country: 'Canada',
    lengthKm: 4.361,
    totalLaps: 70,
    baseLapTime: 74.0,
    pitLaneTime: 22.0,
    tireWearMultiplier: 1.0,
    overtakeDifficulty: 0.35,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Circuit de Barcelona-Catalunya',
    country: 'Spain',
    lengthKm: 4.657,
    totalLaps: 66,
    baseLapTime: 78.0,
    pitLaneTime: 23.0,
    tireWearMultiplier: 1.2,
    overtakeDifficulty: 0.6,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Red Bull Ring',
    country: 'Austria',
    lengthKm: 4.318,
    totalLaps: 71,
    baseLapTime: 66.5,
    pitLaneTime: 21.5,
    tireWearMultiplier: 1.05,
    overtakeDifficulty: 0.35,
    drsZones: 3,
    sectors: 3,
  },
  {
    name: 'Silverstone Circuit',
    country: 'Great Britain',
    lengthKm: 5.891,
    totalLaps: 52,
    baseLapTime: 87.0,
    pitLaneTime: 24.0,
    tireWearMultiplier: 1.15,
    overtakeDifficulty: 0.45,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Hungaroring',
    country: 'Hungary',
    lengthKm: 4.381,
    totalLaps: 70,
    baseLapTime: 78.5,
    pitLaneTime: 22.0,
    tireWearMultiplier: 1.0,
    overtakeDifficulty: 0.75,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Circuit de Spa-Francorchamps',
    country: 'Belgium',
    lengthKm: 7.004,
    totalLaps: 44,
    baseLapTime: 106.0,
    pitLaneTime: 26.0,
    tireWearMultiplier: 1.1,
    overtakeDifficulty: 0.3,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Circuit Zandvoort',
    country: 'Netherlands',
    lengthKm: 4.259,
    totalLaps: 72,
    baseLapTime: 71.5,
    pitLaneTime: 22.5,
    tireWearMultiplier: 1.1,
    overtakeDifficulty: 0.7,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Autodromo Nazionale Monza',
    country: 'Italy',
    lengthKm: 5.793,
    totalLaps: 53,
    baseLapTime: 82.0,
    pitLaneTime: 26.0,
    tireWearMultiplier: 0.9,
    overtakeDifficulty: 0.25,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Marina Bay Street Circuit',
    country: 'Singapore',
    lengthKm: 4.940,
    totalLaps: 62,
    baseLapTime: 98.0,
    pitLaneTime: 24.0,
    tireWearMultiplier: 1.0,
    overtakeDifficulty: 0.65,
    drsZones: 3,
    sectors: 3,
  },
  {
    name: 'Circuit of the Americas',
    country: 'USA',
    lengthKm: 5.513,
    totalLaps: 56,
    baseLapTime: 96.0,
    pitLaneTime: 23.5,
    tireWearMultiplier: 1.1,
    overtakeDifficulty: 0.4,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Interlagos Circuit',
    country: 'Brazil',
    lengthKm: 4.309,
    totalLaps: 71,
    baseLapTime: 71.0,
    pitLaneTime: 22.0,
    tireWearMultiplier: 1.1,
    overtakeDifficulty: 0.35,
    drsZones: 2,
    sectors: 3,
  },
  {
    name: 'Yas Marina Circuit',
    country: 'Abu Dhabi',
    lengthKm: 5.281,
    totalLaps: 58,
    baseLapTime: 86.0,
    pitLaneTime: 23.0,
    tireWearMultiplier: 1.05,
    overtakeDifficulty: 0.4,
    drsZones: 2,
    sectors: 3,
  },
];

/**
 * Get track by name (case-insensitive partial match)
 */
export function getTrack(name: string): TrackConfig | undefined {
  return TRACKS.find(
    (t) => t.name.toLowerCase().includes(name.toLowerCase())
  );
}

/**
 * Get track by index (round number, 0-based)
 */
export function getTrackByRound(round: number): TrackConfig {
  return TRACKS[round % TRACKS.length];
}
